---
env:
  browser: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
rules:
  no-control-regex: "off"
  no-console:
    - warn
    - allow:
        - error
  '@typescript-eslint/no-unused-vars':
    - error
    - args: none